FROM almalinux:9.4
RUN dnf install -y openssh-clients podman podman-docker
RUN dnf install python3 python3-pip && python3 -m pip install --upgrade pip \
    && pip3 install podman-compose
CMD [ "/bin/bash" ]